import React, { useEffect, useState } from "react";
import { FiCheck, FiChevronLeft, FiChevronRight, FiLock, FiX } from "react-icons/fi";
import { getMonthValue, isFutureMonth, monthLabel } from "../../utils/date";

const months = ["January","February","March","April","May","June","July","August","September","October","November","December"];

export default function MonthPickerOverlay({ open, selectedMonth, onSelect, onClose }) {
  const [year, setYear] = useState(Number(selectedMonth?.slice(0, 4)) || new Date().getFullYear());
  useEffect(() => { if (open) setYear(Number(selectedMonth?.slice(0, 4)) || new Date().getFullYear()); }, [open, selectedMonth]);
  useEffect(() => { if (!open) return undefined; const key = (e) => e.key === "Escape" && onClose?.(); document.addEventListener("keydown", key); const old = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", key); document.body.style.overflow = old; }; }, [open, onClose]);
  if (!open) return null;
  const current = getMonthValue();
  return <div className="fixed inset-0 z-[95] flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose?.(); }}><div className="w-full max-w-[760px] rounded-[28px] border border-slate-200 bg-white p-5 shadow-2xl dark:border-slate-700 dark:bg-[#0d1a2b] sm:p-7"><div className="relative flex items-center justify-center"><div className="flex items-center gap-4"><button type="button" onClick={() => setYear((v) => v - 1)} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 hover:border-teal-300 dark:border-slate-700 dark:bg-white/[0.04]"><FiChevronLeft /></button><div className="min-w-28 text-center"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">Select month</p><p className="text-3xl font-bold text-slate-950 dark:text-white">{year}</p></div><button type="button" onClick={() => setYear((v) => v + 1)} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 hover:border-teal-300 dark:border-slate-700 dark:bg-white/[0.04]"><FiChevronRight /></button></div><button type="button" onClick={onClose} className="absolute right-0 rounded-xl p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-white/[0.06]"><FiX className="h-5 w-5" /></button></div><div className="mt-7 grid grid-cols-3 gap-2.5 sm:grid-cols-4 sm:gap-4">{months.map((name, index) => { const value = `${year}-${String(index + 1).padStart(2, "0")}`; const disabled = isFutureMonth(value); const selected = value === selectedMonth; return <button key={value} type="button" disabled={disabled} onClick={() => { onSelect?.(value); onClose?.(); }} className={`relative flex min-h-[76px] flex-col items-center justify-center rounded-2xl border p-3 transition sm:min-h-[94px] ${selected ? "border-teal-500 bg-teal-50 text-teal-800 ring-2 ring-teal-500/15 dark:bg-teal-400/10 dark:text-teal-200" : disabled ? "cursor-not-allowed border-slate-200 bg-slate-100 text-slate-300 opacity-60 dark:border-white/[0.05] dark:bg-white/[0.025] dark:text-slate-600" : "border-slate-200 bg-white text-slate-700 shadow-sm hover:-translate-y-0.5 hover:border-teal-300 hover:bg-teal-50/60 dark:border-white/[0.08] dark:bg-white/[0.035] dark:text-slate-200"}`}><span className="text-xs font-bold sm:text-sm">{name}</span>{value === current && !disabled && <span className="mt-1 text-[8px] font-bold uppercase tracking-wider text-teal-600">Current</span>}{disabled && <FiLock className="mt-1.5 h-3.5 w-3.5" />}{selected && <span className="absolute right-2 top-2 flex h-5 w-5 items-center justify-center rounded-full bg-teal-500 text-white"><FiCheck className="h-3 w-3" /></span>}</button>; })}</div><p className="mt-5 text-center text-[10px] text-slate-400">Future months are disabled. Currently viewing {monthLabel(selectedMonth)}.</p></div></div>;
}
