import React from "react";
import { FiBell, FiMenu, FiMoon, FiSearch, FiSun } from "react-icons/fi";
import { Link, useLocation } from "react-router";
import Logo from "../../assets/logo.webp";
import { useAuth } from "../../contexts/AuthContext";
import WorkspaceSwitcher from "../workspace/WorkspaceSwitcher";

const titles = { "/dashboard": "Dashboard", "/transactions": "Transactions", "/wallets": "Wallets", "/budgets": "Budgets", "/reports": "Reports", "/members": "Members", "/profile": "Profile", "/settings": "Settings" };

export default function Topbar({ onMenuClick, theme, onThemeToggle }) {
  const location = useLocation();
  const { profile } = useAuth();
  const title = titles[location.pathname] || "PesoWise";
  return <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/92 backdrop-blur-xl dark:border-white/[0.06] dark:bg-[#07111f]/92"><div className="flex h-16 items-center gap-3 px-4 sm:px-6 lg:h-[72px] lg:px-8"><Link to="/dashboard" className="flex min-w-0 items-center gap-2 lg:hidden"><img src={Logo} alt="PesoWise" className="h-8 w-8 rounded-lg object-contain" /><span className="text-sm font-extrabold text-slate-950 dark:text-white">PesoWise</span></Link><div className="hidden min-w-[130px] lg:block"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-teal-600 dark:text-teal-400">Active page</p><h1 className="mt-0.5 truncate text-base font-bold text-slate-950 dark:text-white">{title}</h1></div><div className="relative hidden min-w-[220px] max-w-[520px] flex-1 lg:block"><FiSearch className="pointer-events-none absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input type="search" placeholder="Search transactions, wallets…" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-10 pr-4 text-sm outline-none transition focus:border-teal-400 focus:bg-white focus:ring-4 focus:ring-teal-500/10 dark:border-slate-700 dark:bg-white/[0.04] dark:text-white" /></div><div className="ml-auto hidden w-72 xl:block"><WorkspaceSwitcher compact /></div><div className="ml-auto flex items-center gap-1.5 xl:ml-0"><button type="button" onClick={onThemeToggle} className="flex h-10 w-10 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-white/[0.06]" aria-label="Toggle theme">{theme === "dark" ? <FiSun className="h-[17px] w-[17px]" /> : <FiMoon className="h-[17px] w-[17px]" />}</button><Link to="/invitations" className="relative flex h-10 w-10 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-white/[0.06]" aria-label="Invitations"><FiBell className="h-[17px] w-[17px]" /><span className="absolute right-2.5 top-2.5 h-1.5 w-1.5 rounded-full bg-amber-400" /></Link><Link to="/profile" className="hidden rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700 dark:border-slate-700 dark:bg-white/[0.04] dark:text-slate-200 sm:block">{profile?.full_name?.split(" ")[0] || "Profile"}</Link><button type="button" onClick={onMenuClick} className="flex h-10 w-10 items-center justify-center rounded-xl text-slate-500 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-white/[0.06] lg:hidden" aria-label="Open sidebar"><FiMenu className="h-[18px] w-[18px]" /></button></div></div></header>;
}
