import React, { useCallback, useEffect, useState } from "react";
import { FiClock, FiMail, FiMoreVertical, FiPlus, FiRefreshCw, FiShield, FiTrash2, FiUserCheck, FiUsers } from "react-icons/fi";
import ConfirmDialog from "../components/common/ConfirmDialog";
import EmptyState from "../components/common/EmptyState";
import { Field, inputClass, PrimaryButton, SecondaryButton } from "../components/common/FormControls";
import { ListPageSkeleton } from "../components/common/LoadingStates";
import Modal from "../components/common/Modal";
import PageHeader from "../components/common/PageHeader";
import { useAuth } from "../contexts/AuthContext";
import { useToast } from "../contexts/ToastContext";
import { useWorkspace } from "../contexts/WorkspaceContext";
import { useWorkspaceRealtime } from "../hooks/useWorkspaceRealtime";
import { INVITABLE_ROLES, ROLE_LABELS } from "../lib/constants";
import { invitationService } from "../services/invitationService";
import { memberService } from "../services/memberService";
import { formatDate } from "../utils/date";
import { getFriendlyError } from "../utils/errors";

const realtimeTables = ["workspace_members", "workspace_invitations"];

export default function Members() {
  const { user } = useAuth(); const { activeWorkspace, role, refreshWorkspaces } = useWorkspace(); const toast = useToast();
  const [members, setMembers] = useState([]); const [invitations, setInvitations] = useState([]); const [loading, setLoading] = useState(true); const [inviteOpen, setInviteOpen] = useState(false); const [inviteForm, setInviteForm] = useState({ email: "", role: "member" }); const [inviteLoading, setInviteLoading] = useState(false); const [confirm, setConfirm] = useState(null); const [actionLoading, setActionLoading] = useState(false);
  const canManage = ["owner","admin"].includes(role);
  const load = useCallback(async ({ silent = false } = {}) => { if (!silent) setLoading(true); try { const [nextMembers, nextInvites] = await Promise.all([memberService.list(activeWorkspace.id), invitationService.listWorkspaceInvitations(activeWorkspace.id)]); setMembers(nextMembers); setInvitations(nextInvites); } catch (error) { toast.error(getFriendlyError(error)); } finally { setLoading(false); } }, [activeWorkspace.id, toast]);
  useEffect(() => { load(); }, [load]); useWorkspaceRealtime(activeWorkspace.id, realtimeTables, useCallback(() => load({ silent: true }), [load]));
  const invite = async (event) => { event.preventDefault(); setInviteLoading(true); try { await invitationService.invite(activeWorkspace.id, inviteForm.email, inviteForm.role); toast.success("Invitation created. Email delivery runs when the Supabase Edge Function is configured."); setInviteOpen(false); setInviteForm({ email: "", role: "member" }); load({ silent: true }); } catch (error) { toast.error(getFriendlyError(error)); } finally { setInviteLoading(false); } };
  const changeRole = async (member, nextRole) => { try { await memberService.changeRole(activeWorkspace.id, member.user_id, nextRole); toast.success("Member role updated."); load({ silent: true }); } catch (error) { toast.error(getFriendlyError(error)); } };
  const runConfirm = async () => { if (!confirm) return; setActionLoading(true); try { if (confirm.type === "remove") await memberService.remove(activeWorkspace.id, confirm.member.user_id); if (confirm.type === "transfer") { await memberService.transferOwnership(activeWorkspace.id, confirm.member.user_id); await refreshWorkspaces(); } if (confirm.type === "cancel") await invitationService.cancel(confirm.invitation.id); toast.success(confirm.type === "transfer" ? "Ownership transferred." : confirm.type === "cancel" ? "Invitation canceled." : "Member removed."); setConfirm(null); load({ silent: true }); } catch (error) { toast.error(getFriendlyError(error)); } finally { setActionLoading(false); } };
  const resend = async (invitation) => { try { await invitationService.invite(activeWorkspace.id, invitation.email, invitation.role); toast.success("Invitation renewed for another 7 days."); load({ silent: true }); } catch (error) { toast.error(getFriendlyError(error)); } };
  if (loading) return <ListPageSkeleton rows={6} />;
  const pending = invitations.filter((invite) => invite.status === "pending" && new Date(invite.expires_at) > new Date());
  return <div><PageHeader eyebrow={activeWorkspace.name} title="Workspace members" description="Every person uses their own secure account while collaborating in the same shared budget." actions={canManage && <PrimaryButton onClick={() => setInviteOpen(true)}><FiPlus /> Invite member</PrimaryButton>} />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-[#0d1a2b]"><div className="border-b border-slate-100 px-5 py-4 dark:border-slate-800"><h2 className="text-sm font-bold text-slate-900 dark:text-white">Members</h2><p className="mt-1 text-xs text-slate-400">{members.length} person{members.length === 1 ? "" : "s"} can access this workspace</p></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{members.map((member) => { const isSelf = member.user_id === user.id; const initials = (member.profile?.full_name || member.profile?.email || "U").split(/\s+/).map((p) => p[0]).join("").slice(0,2).toUpperCase(); const canAct = canManage && member.role !== "owner" && !isSelf && !(role === "admin" && member.role === "admin"); return <div key={member.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-sky-500 to-teal-400 text-xs font-bold text-white">{initials}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-bold text-slate-900 dark:text-white">{member.profile?.full_name || "Unnamed member"}</p>{isSelf && <span className="rounded-full bg-teal-50 px-2 py-0.5 text-[9px] font-bold text-teal-700 dark:bg-teal-400/10 dark:text-teal-300">You</span>}</div><p className="mt-0.5 truncate text-xs text-slate-400">{member.profile?.email}</p><p className="mt-1 text-[10px] text-slate-400">Joined {formatDate(member.joined_at?.slice(0,10))}</p></div><div className="flex items-center gap-2">{canAct ? <select value={member.role} onChange={(e) => changeRole(member,e.target.value)} className="h-9 rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold capitalize dark:border-slate-700 dark:bg-white/[0.04]">{INVITABLE_ROLES.map((nextRole) => <option key={nextRole} value={nextRole}>{ROLE_LABELS[nextRole]}</option>)}</select> : <span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1.5 text-[10px] font-bold text-slate-600 dark:bg-white/[0.06] dark:text-slate-300"><FiShield /> {ROLE_LABELS[member.role]}</span>}{canAct && <button type="button" onClick={() => setConfirm({ type:"remove", member })} className="rounded-xl p-2.5 text-slate-400 hover:bg-rose-50 hover:text-rose-500 dark:hover:bg-rose-400/10"><FiTrash2 /></button>}{role === "owner" && member.role !== "owner" && !isSelf && <button type="button" onClick={() => setConfirm({ type:"transfer", member })} className="rounded-xl p-2.5 text-slate-400 hover:bg-teal-50 hover:text-teal-600 dark:hover:bg-teal-400/10" title="Transfer ownership"><FiUserCheck /></button>}</div></div>; })}</div></section>
      <aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#0d1a2b]"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900 dark:text-white">Pending invitations</h2><p className="mt-1 text-xs text-slate-400">Waiting for a response</p></div><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-50 text-amber-500 dark:bg-amber-400/10"><FiClock /></span></div>{pending.length === 0 ? <div className="py-10 text-center"><FiMail className="mx-auto h-6 w-6 text-slate-300 dark:text-slate-700" /><p className="mt-2 text-xs text-slate-400">No pending invitations.</p></div> : <div className="mt-4 space-y-3">{pending.map((invitation) => <div key={invitation.id} className="rounded-2xl bg-slate-50 p-3 dark:bg-white/[0.035]"><p className="truncate text-xs font-bold text-slate-800 dark:text-white">{invitation.email}</p><p className="mt-1 text-[10px] capitalize text-slate-400">{invitation.role} · Expires {formatDate(invitation.expires_at.slice(0,10))}</p>{canManage && <div className="mt-3 flex gap-2"><button type="button" onClick={() => resend(invitation)} className="flex h-8 flex-1 items-center justify-center gap-1.5 rounded-lg bg-white text-[10px] font-bold text-teal-600 shadow-sm dark:bg-white/[0.06] dark:text-teal-300"><FiRefreshCw /> Resend</button><button type="button" onClick={() => setConfirm({ type:"cancel", invitation })} className="flex h-8 flex-1 items-center justify-center gap-1.5 rounded-lg bg-white text-[10px] font-bold text-rose-500 shadow-sm dark:bg-white/[0.06]"><FiTrash2 /> Cancel</button></div>}</div>)}</div>}</aside></div>
    {members.length === 1 && <div className="mt-6"><EmptyState icon={FiUsers} compact title="You’re currently the only member" description="Invite family members, partners, or teammates to manage this budget together." actionLabel={canManage ? "Invite member" : undefined} onAction={() => setInviteOpen(true)} /></div>}
    <Modal open={inviteOpen} onClose={() => setInviteOpen(false)} title="Invite member" description="The person will use their own PesoWise account to access this workspace." footer={<div className="flex justify-end gap-2"><SecondaryButton onClick={() => setInviteOpen(false)}>Cancel</SecondaryButton><PrimaryButton type="submit" form="invite-form" loading={inviteLoading}>Send invitation</PrimaryButton></div>}><form id="invite-form" onSubmit={invite} className="space-y-5"><Field label="Email address" required><input type="email" required value={inviteForm.email} onChange={(e) => setInviteForm((v) => ({ ...v, email:e.target.value }))} className={inputClass} placeholder="maria@example.com" /></Field><Field label="Role" required><select value={inviteForm.role} onChange={(e) => setInviteForm((v) => ({ ...v, role:e.target.value }))} className={inputClass}>{INVITABLE_ROLES.map((nextRole) => <option key={nextRole} value={nextRole}>{ROLE_LABELS[nextRole]}</option>)}</select></Field><div className="rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500 dark:bg-white/[0.035]"><strong className="text-slate-700 dark:text-slate-200">Member</strong> can add and edit their own transactions. <strong className="text-slate-700 dark:text-slate-200">Viewer</strong> is read-only. <strong className="text-slate-700 dark:text-slate-200">Admin</strong> can manage wallets, budgets, and regular members.</div></form></Modal>
    <ConfirmDialog open={Boolean(confirm)} onClose={() => setConfirm(null)} onConfirm={runConfirm} title={confirm?.type === "transfer" ? "Transfer workspace ownership?" : confirm?.type === "cancel" ? "Cancel invitation?" : "Remove member?"} description={confirm?.type === "transfer" ? `${confirm.member?.profile?.full_name} will become the primary owner. You will become an Admin.` : confirm?.type === "cancel" ? `The invitation for ${confirm.invitation?.email} will no longer be valid.` : `${confirm?.member?.profile?.full_name} will lose access to this workspace.`} confirmLabel={confirm?.type === "transfer" ? "Transfer ownership" : confirm?.type === "cancel" ? "Cancel invitation" : "Remove member"} loading={actionLoading} danger={confirm?.type !== "transfer"} />
  </div>;
}
