import React, { useEffect, useState } from "react";
import { FiAlertTriangle, FiLogOut, FiPlus, FiSave, FiTrash2 } from "react-icons/fi";
import { useNavigate } from "react-router";
import ConfirmDialog from "../components/common/ConfirmDialog";
import { SkeletonBlock } from "../components/common/LoadingStates";
import { Field, inputClass, PrimaryButton, SecondaryButton, textareaClass } from "../components/common/FormControls";
import Modal from "../components/common/Modal";
import PageHeader from "../components/common/PageHeader";
import InstallAppAction from "../components/pwa/InstallAppAction";
import { useAuth } from "../contexts/AuthContext";
import { useToast } from "../contexts/ToastContext";
import { useWorkspace } from "../contexts/WorkspaceContext";
import { categoryService } from "../services/categoryService";
import { workspaceService } from "../services/workspaceService";
import { getFriendlyError } from "../utils/errors";

export default function Settings() {
  const { user } = useAuth(); const { activeWorkspace, role, refreshWorkspaces } = useWorkspace(); const toast = useToast(); const navigate = useNavigate();
  const [form, setForm] = useState({ name: activeWorkspace.name, description: activeWorkspace.description || "", currency: activeWorkspace.currency, memberCanManageWallets: Boolean(activeWorkspace.settings?.member_can_manage_wallets) });
  const [saving, setSaving] = useState(false); const [categories, setCategories] = useState([]); const [categoryLoading, setCategoryLoading] = useState(true); const [categoryOpen, setCategoryOpen] = useState(false); const [categoryForm, setCategoryForm] = useState({ name:"", type:"expense", color:"#14b8a6" }); const [categorySaving, setCategorySaving] = useState(false); const [confirm, setConfirm] = useState(null); const [dangerLoading, setDangerLoading] = useState(false);
  const canEdit = ["owner","admin"].includes(role); const isOwner = role === "owner";
  useEffect(() => {
    let active = true;
    setForm({ name:activeWorkspace.name, description:activeWorkspace.description || "", currency:activeWorkspace.currency, memberCanManageWallets:Boolean(activeWorkspace.settings?.member_can_manage_wallets) });
    setCategoryLoading(true);
    categoryService.list(activeWorkspace.id)
      .then((next) => { if (active) setCategories(next); })
      .catch((error) => { if (active) toast.error(getFriendlyError(error, "Could not load categories.")); })
      .finally(() => { if (active) setCategoryLoading(false); });
    return () => { active = false; };
  }, [activeWorkspace, toast]);
  const save = async (event) => { event.preventDefault(); setSaving(true); try { await workspaceService.update(activeWorkspace.id, { name:form.name, description:form.description, currency:form.currency, settings:{ ...activeWorkspace.settings, member_can_manage_wallets:form.memberCanManageWallets } }); await refreshWorkspaces(); toast.success("Workspace settings saved."); } catch (error) { toast.error(getFriendlyError(error)); } finally { setSaving(false); } };
  const createCategory = async (event) => { event.preventDefault(); if (!categoryForm.name.trim()) return toast.error("Enter a category name."); setCategorySaving(true); try { const created = await categoryService.create(activeWorkspace.id, user.id, categoryForm); setCategories((current) => [...current,created].sort((a,b)=>a.name.localeCompare(b.name))); toast.success("Category created."); setCategoryOpen(false); setCategoryForm({name:"",type:"expense",color:"#14b8a6"}); } catch (error) { toast.error(getFriendlyError(error)); } finally { setCategorySaving(false); } };
  const runDanger = async () => { setDangerLoading(true); try { if (confirm === "delete") { await workspaceService.remove(activeWorkspace.id); toast.success("Workspace deleted."); } else { await workspaceService.leave(activeWorkspace.id); toast.success("You left the workspace."); } await refreshWorkspaces({ keepSelection:false }); navigate("/dashboard", { replace:true }); } catch (error) { toast.error(getFriendlyError(error)); } finally { setDangerLoading(false); setConfirm(null); } };
  return <div><PageHeader eyebrow={activeWorkspace.name} title="Workspace settings" description="Manage the workspace identity, currency, categories, wallet permissions, and membership actions." />
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><form onSubmit={save} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#0d1a2b] sm:p-6"><h2 className="text-sm font-bold text-slate-900 dark:text-white">General</h2><div className="mt-5 space-y-5"><Field label="Workspace name" required><input disabled={!canEdit} value={form.name} onChange={(e) => setForm((v)=>({...v,name:e.target.value}))} className={inputClass} /></Field><Field label="Description"><textarea disabled={!canEdit} value={form.description} onChange={(e)=>setForm((v)=>({...v,description:e.target.value}))} className={textareaClass} /></Field><Field label="Currency"><select disabled={!canEdit} value={form.currency} onChange={(e)=>setForm((v)=>({...v,currency:e.target.value}))} className={inputClass}><option value="PHP">PHP — Philippine Peso</option><option value="USD">USD — US Dollar</option><option value="EUR">EUR — Euro</option></select></Field><label className="flex items-start gap-3 rounded-2xl bg-slate-50 p-4 dark:bg-white/[0.035]"><input type="checkbox" disabled={!canEdit} checked={form.memberCanManageWallets} onChange={(e)=>setForm((v)=>({...v,memberCanManageWallets:e.target.checked}))} className="mt-1 h-4 w-4 accent-teal-500" /><span><span className="block text-sm font-semibold text-slate-800 dark:text-white">Allow Members to create and edit wallets</span><span className="mt-1 block text-xs leading-5 text-slate-400">Members can always add transactions to available wallets. This setting grants extra wallet-management access.</span></span></label>{canEdit && <PrimaryButton type="submit" loading={saving}><FiSave /> Save settings</PrimaryButton>}</div></form>
      <aside className="space-y-6"><InstallAppAction variant="card" /><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-[#0d1a2b]"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900 dark:text-white">Categories</h2><p className="mt-1 text-xs text-slate-400">{categoryLoading ? "Loading categories…" : `${categories.length} active categories`}</p></div>{canEdit && <button onClick={()=>setCategoryOpen(true)} className="flex h-9 w-9 items-center justify-center rounded-xl bg-teal-50 text-teal-600 dark:bg-teal-400/10 dark:text-teal-300"><FiPlus /></button>}</div><div className="mt-4 flex max-h-72 flex-wrap gap-2 overflow-y-auto">{categoryLoading ? [72, 96, 84, 112, 78, 104].map((width, index) => <SkeletonBlock key={index} className="h-7 rounded-full" style={{ width }} />) : categories.map((category)=><span key={category.id} className="rounded-full border border-slate-200 px-3 py-1.5 text-[10px] font-semibold text-slate-600 dark:border-slate-700 dark:text-slate-300" style={{ borderLeftColor:category.color, borderLeftWidth:3 }}>{category.name} · {category.type}</span>)}</div></section><section className="rounded-2xl border border-rose-200 bg-rose-50/60 p-5 dark:border-rose-400/15 dark:bg-rose-400/[0.05]"><h2 className="flex items-center gap-2 text-sm font-bold text-rose-700 dark:text-rose-300"><FiAlertTriangle /> Workspace actions</h2><p className="mt-2 text-xs leading-5 text-rose-600/75 dark:text-rose-200/60">Owners must transfer ownership before leaving. Only the primary owner can permanently delete the workspace.</p><div className="mt-4 space-y-2">{!isOwner && <SecondaryButton onClick={()=>setConfirm("leave")} className="w-full border-rose-200 text-rose-600"><FiLogOut /> Leave workspace</SecondaryButton>}{isOwner && <SecondaryButton onClick={()=>setConfirm("delete")} className="w-full border-rose-200 text-rose-600"><FiTrash2 /> Delete workspace</SecondaryButton>}</div></section></aside></div>
    <Modal open={categoryOpen} onClose={()=>setCategoryOpen(false)} title="Create category" description="Custom categories are available only inside this workspace." footer={<div className="flex justify-end gap-2"><SecondaryButton onClick={()=>setCategoryOpen(false)}>Cancel</SecondaryButton><PrimaryButton type="submit" form="category-form" loading={categorySaving}>Create category</PrimaryButton></div>}><form id="category-form" onSubmit={createCategory} className="space-y-5"><Field label="Category name" required><input value={categoryForm.name} onChange={(e)=>setCategoryForm((v)=>({...v,name:e.target.value}))} className={inputClass} placeholder="Pet Care" /></Field><Field label="Type"><select value={categoryForm.type} onChange={(e)=>setCategoryForm((v)=>({...v,type:e.target.value}))} className={inputClass}><option value="expense">Expense</option><option value="income">Income</option></select></Field><Field label="Color"><input type="color" value={categoryForm.color} onChange={(e)=>setCategoryForm((v)=>({...v,color:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 bg-white p-1.5 dark:border-slate-700 dark:bg-white/[0.04]" /></Field></form></Modal>
    <ConfirmDialog open={Boolean(confirm)} onClose={()=>setConfirm(null)} onConfirm={runDanger} title={confirm === "delete" ? "Delete workspace permanently?" : "Leave this workspace?"} description={confirm === "delete" ? "All wallets, transactions, budgets, invitations, and activity will be permanently deleted for every member." : "You will lose access to this workspace and its financial records."} confirmLabel={confirm === "delete" ? "Delete workspace" : "Leave workspace"} loading={dangerLoading} danger />
  </div>;
}
